# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '11'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: s4u/maven-settings-action@v2.8.0
      - name: Build with Maven
        run: mvn -B -ntp package -Pnative --file pom.xml
      - name: Publish to GitHub Packages Apache Maven
        run: |
          mvn deploy -B -ntp
          mvn deploy -B -ntp -Dfile=target/remotedev-*-runner* -Dclassifier=linux-amd64
        env:
          GITHUB_TOKEN: ${{ github.token }}
